// Current ISO 4217 currencies missing from the original package catalog.
// Numeric codes and minor units are sourced from the ISO 4217 maintenance
// agency's List One, published by SIX.
final List<Map<String, dynamic>> additionalCurrencies = [
  _currency('AWG', 'Aruban Florin', 'Afl.', 'AW', 533, 2, ['Aruba']),
  _currency('BSD', 'Bahamian Dollar', r'B$', 'BS', 44, 2, ['Bahamas']),
  _currency(
    'CVE',
    'Cabo Verde Escudo',
    'Esc',
    'CV',
    132,
    2,
    ['Cabo Verde', 'Cape Verde'],
    symbolOnLeft: false,
  ),
  _currency(
    'DJF',
    'Djibouti Franc',
    'Fdj',
    'DJ',
    262,
    0,
    ['Djibouti'],
    symbolOnLeft: false,
  ),
  _currency('ERN', 'Eritrean Nakfa', 'Nfk', 'ER', 232, 2, ['Eritrea']),
  _currency('FJD', 'Fiji Dollar', r'FJ$', 'FJ', 242, 2, ['Fiji']),
  _currency('FKP', 'Falkland Islands Pound', '£', 'FK', 238, 2, [
    'Falkland Islands',
    'Malvinas',
  ]),
  _currency('GIP', 'Gibraltar Pound', '£', 'GI', 292, 2, ['Gibraltar']),
  _currency(
    'GNF',
    'Guinean Franc',
    'FG',
    'GN',
    324,
    0,
    ['Guinea'],
    symbolOnLeft: false,
  ),
  _currency('HNL', 'Honduran Lempira', 'L', 'HN', 340, 2, ['Honduras']),
  _currency('IRR', 'Iranian Rial', '﷼', 'IR', 364, 2, ['Iran']),
  _currency(
    'KMF',
    'Comorian Franc',
    'CF',
    'KM',
    174,
    0,
    ['Comoros'],
    symbolOnLeft: false,
  ),
  _currency('KPW', 'North Korean Won', '₩', 'KP', 408, 2, [
    'North Korea',
    'DPRK',
  ]),
  _currency('LSL', 'Lesotho Loti', 'L', 'LS', 426, 2, ['Lesotho']),
  _currency('LYD', 'Libyan Dinar', 'LD', 'LY', 434, 3, ['Libya']),
  _currency('MOP', 'Macanese Pataca', r'MOP$', 'MO', 446, 2, [
    'Macao',
    'Macau',
  ]),
  _currency('MRU', 'Mauritanian Ouguiya', 'UM', 'MR', 929, 2, [
    'Mauritania',
    'MRO',
  ]),
  _currency('PAB', 'Panamanian Balboa', 'B/.', 'PA', 590, 2, ['Panama']),
  _currency('SBD', 'Solomon Islands Dollar', r'SI$', 'SB', 90, 2, [
    'Solomon Islands',
  ]),
  _currency('SDG', 'Sudanese Pound', 'SDG', 'SD', 938, 2, ['Sudan']),
  _currency('SHP', 'Saint Helena Pound', '£', 'SH', 654, 2, [
    'Saint Helena',
    'Ascension Island',
    'Tristan da Cunha',
  ]),
  _currency('SLE', 'Sierra Leonean Leone', 'Le', 'SL', 925, 2, [
    'Sierra Leone',
    'SLL',
  ]),
  _currency('SSP', 'South Sudanese Pound', 'SSP', 'SS', 728, 2, [
    'South Sudan',
  ]),
  _currency('STN', 'São Tomé and Príncipe Dobra', 'Db', 'ST', 930, 2, [
    'Sao Tome and Principe',
    'São Tomé and Príncipe',
    'STD',
  ]),
  _currency('SVC', 'El Salvador Colón', '₡', 'SV', 222, 2, ['El Salvador']),
  _currency('SZL', 'Eswatini Lilangeni', 'L', 'SZ', 748, 2, [
    'Eswatini',
    'Swaziland',
  ]),
  _currency(
    'TJS',
    'Tajikistani Somoni',
    'SM',
    'TJ',
    972,
    2,
    ['Tajikistan'],
    symbolOnLeft: false,
  ),
  _currency('TMT', 'Turkmenistan Manat', 'm', 'TM', 934, 2, ['Turkmenistan']),
  _currency(
    'UZS',
    'Uzbekistan Sum',
    "so'm",
    'UZ',
    860,
    2,
    [
      'Uzbekistan',
      'Uzbekistani som',
      'Uzbekistani sum',
      "so'm",
      'som',
      'sum',
    ],
    symbolOnLeft: false,
  ),
  _currency('VES', 'Venezuelan Bolívar', 'Bs.', 'VE', 928, 2, [
    'Venezuela',
    'Bolívar Soberano',
    'Bolivar Soberano',
    'VEF',
  ]),
  _currency(
    'VUV',
    'Vanuatu Vatu',
    'VT',
    'VU',
    548,
    0,
    ['Vanuatu'],
    symbolOnLeft: false,
  ),
  _currency('WST', 'Samoan Tala', r'WS$', 'WS', 882, 2, ['Samoa']),
  _currency('XCG', 'Caribbean Guilder', 'Cg.', 'CW', 532, 2, [
    'Curaçao',
    'Curacao',
    'Sint Maarten',
    'Netherlands Antillean guilder',
    'ANG',
  ]),
  _currency(
    'XPF',
    'CFP Franc',
    '₣',
    'PF',
    953,
    0,
    ['French Polynesia', 'New Caledonia', 'Wallis and Futuna'],
    symbolOnLeft: false,
  ),
  _currency('ZWG', 'Zimbabwe Gold', 'ZiG', 'ZW', 924, 2, [
    'Zimbabwe',
    'ZiG',
    'ZWL',
  ]),
];

Map<String, dynamic> _currency(
  String code,
  String name,
  String symbol,
  String flag,
  int number,
  int decimalDigits,
  List<String> searchTerms, {
  bool symbolOnLeft = true,
  bool spaceBetweenAmountAndSymbol = true,
}) {
  return {
    'code': code,
    'name': name,
    'symbol': symbol,
    'flag': flag,
    'decimal_digits': decimalDigits,
    'number': number,
    'name_plural': name,
    'thousands_separator': ',',
    'decimal_separator': '.',
    'space_between_amount_and_symbol': spaceBetweenAmountAndSymbol,
    'symbol_on_left': symbolOnLeft,
    'search_terms': searchTerms,
  };
}
